package com.cmc.meeron.attendee.application.port.in.response;

import java.util.List;

public class MeetingTeamAttendeesResponseDtoV2Builder {

    public static MeetingTeamAttendeesResponseDtoV2 build() {
        return MeetingTeamAttendeesResponseDtoV2.builder()
                .attends(List.of(
                        AttendeeResponseDto.builder()
                                .attendeeId(1L)
                                .meetingId(1L)
                                .meetingAdmin(true)
                                .attendStatus("ATTEND")
                                .attendeeWorkspaceUserResponseDto(AttendeeWorkspaceUserResponseDto.builder()
                                        .workspaceUserId(1L)
                                        .workspaceId(1L)
                                        .isWorkspaceAdmin(false)
                                        .nickname("테스트1")
                                        .position("프론트엔드")
                                        .profileImageUrl("https://test.com/123")
                                        .email("test1@test.com")
                                        .phone("010-1234-1234")
                                        .build())
                                .build(),
                        AttendeeResponseDto.builder()
                                .attendeeId(2L)
                                .meetingId(1L)
                                .meetingAdmin(false)
                                .attendStatus("ATTEND")
                                .attendeeWorkspaceUserResponseDto(AttendeeWorkspaceUserResponseDto.builder()
                                        .workspaceUserId(2L)
                                        .workspaceId(1L)
                                        .isWorkspaceAdmin(false)
                                        .nickname("테스트2")
                                        .position("프론트엔드")
                                        .profileImageUrl("https://test.com/143")
                                        .email("test2@test.com")
                                        .phone("010-1234-1235")
                                        .build())
                                .build()))
                .absents(List.of(
                        AttendeeResponseDto.builder()
                                .attendeeId(3L)
                                .meetingId(1L)
                                .meetingAdmin(true)
                                .attendStatus("ABSENT")
                                .attendeeWorkspaceUserResponseDto(AttendeeWorkspaceUserResponseDto.builder()
                                        .workspaceUserId(4L)
                                        .workspaceId(1L)
                                        .isWorkspaceAdmin(false)
                                        .nickname("테스트4")
                                        .position("백엔드")
                                        .profileImageUrl("https://test.com/121")
                                        .email("test3@test.com")
                                        .phone("010-3234-1234")
                                        .build())
                                .build()
                ))
                .unknowns(List.of(
                        AttendeeResponseDto.builder()
                                .attendeeId(4L)
                                .meetingId(1L)
                                .meetingAdmin(true)
                                .attendStatus("UNKNOWN")
                                .attendeeWorkspaceUserResponseDto(AttendeeWorkspaceUserResponseDto.builder()
                                        .workspaceUserId(12L)
                                        .workspaceId(1L)
                                        .isWorkspaceAdmin(false)
                                        .nickname("테스트4")
                                        .position("iOS")
                                        .profileImageUrl("https://test.com/523")
                                        .email("test4@test.com")
                                        .phone("010-5234-1234")
                                        .build())
                                .build()
                ))
                .build();
    }
}
